---
app_hostname: dev.box
app_nginx_port: 80
app_project_path: /srv/share
app_relative_webroot: web
app_cache_path: /dev/shm/symfony/cache
app_log_path: /var/log/symfony
app_front_controller: app.php
app_max_body_size: 512M
app_fpm_timeout: 300
app_parameters_database_host: 10.0.0.10
app_parameters_database_port: 3306
app_parameters_database_name: symfony
app_parameters_database_user: symfony
app_parameters_database_password: "{{ lookup('env','APP_MYSQL_PASSWORD')|default('') }}"